### PR TITLE
Support `barrier;`, that is barrier with no qubit args

### LINKED ISSUE #58: No-argument form of `barrier` unsupported in semantic analysis
A program such as
```qasm3
qubit[2] q;
barrier;
```
is [defined by the OQ3 spec to be equivalent to a barrier over all in-scope qubits](https://openqasm.com/language/delays.html#barrier-instruction).  At the moment it fails to convert in semantic analysis:
```text
thread '<unnamed>' panicked at /Users/jake/.cargo/git/checkouts/openqasm3_parser-f3c8808ea3c5b583/45556a9/crates/oq3_semantics/src/syntax_to_semantics.rs:491:18:
called `Option::unwrap()` on a `None` value
```

which is line 491 here: https://github.com/Qiskit/openqasm3_parser/blob/45556a9d2cfb0dd7a805006af3821e8454480a75/crates/oq3_semantics/src/syntax_to_semantics.rs#L488-L496

### PR DESCRIPTION
**Pull request by jlapeyre**
Closes #58

### CODE REVIEW

**Comment by jakelishman** [comment]
For this kind of thing, `&Option<Vec<T>>` is not typically the best return value of the getter - `self.qubits.as_ref()` would let us return a `Option<&[T]>` (`Option<U>: Copy where U: Copy` and immutable references are `Copy`), which a) has one fewer layer of pointer indirection for the caller to retrieve the slice elements and b) generally pattern-matches and binds in a more expected way for a reference.

It's not super important, it just means that in most uses, the caller has to call `Option::as_ref` immediately after.

**Comment by jlapeyre** [comment]
I don't follow 100%. But I get the general idea. For example, this is clearly better to me:
```rust
    pub fn qubits(&self) -> Option<&Vec<TExpr>> {
        self.qubits.as_ref()
    }
```
But it looks like you are asking for something else?

**Comment by jakelishman** [comment]
I'm asking for this:
```
    pub fn qubits(&self) -> Option<&[TExpr]> {
        self.qubits.as_ref()
    }
```
which is more proper Rust and will automatically resolve the type-hint reference.

A `&Vec` is _almost_ never necessary, because all of the interesting things you can do with something that's specifically a `Vec` require mutability, and all the methods that are to do with iterating/viewing items/etc are inherited by `Vec<T>: Deref<Target=[T]>`.  In memory, a `&Vec` is _a pointer to_ a `(pointer, len, capacity)`, whereas a `&[T]` is _directly_ a `(pointer, len)` two-tuple, so there's one less pointer indirection for the caller to access the underlying memory. (Plus, almost everything in Rust wants `&[T]` not `&Vec`, so if you've got an `Option<&Vec>`, you have to call `(&Option)::as_deref()` to coerce the inner value into the slice that's needed.

**Comment by jakelishman** [comment]
Oh sorry, should be `as_deref`

**Comment by jlapeyre** [comment]
Ah ok.

> so there's one less pointer indirection

This is definitely something we want.

**Comment by jlapeyre** [comment]
The compiler was not smart enough in this case to suggest `deref`.

I like the idea of  using idiomatic code, because it serves as a model. and it is only extra effort to learn it the first time (or few times!). Even if in a particular case it is not important for performance.

**Comment by jakelishman** [comment]
That actually could be a reasonable suggestion for an error message for `rustc`, I think.  It's an easy mistake to make, and should be an easy alternative to check for.

**Pull request merged**
