### PR TITLE
Adding from_designator + notes for usage

### LINKED ISSUE #170: Implement function `from_designator` in syntax_to_semantics.rs
Analyzing designators :

* needs to be cleaner, with better error reporting
* is repeated and should be refactored.

This can be done by writing a function `fn from_designator`.

For example the similar small bits of code are repeated in many places:
https://github.com/Qiskit/openqasm3_parser/blob/22b55cc1582f1c98180099dca1f224d0fab11fd8/crates/oq3_semantics/src/syntax_to_semantics.rs#L286

https://github.com/Qiskit/openqasm3_parser/blob/22b55cc1582f1c98180099dca1f224d0fab11fd8/crates/oq3_semantics/src/syntax_to_semantics.rs#L409

https://github.com/Qiskit/openqasm3_parser/blob/22b55cc1582f1c98180099dca1f224d0fab11fd8/crates/oq3_semantics/src/syntax_to_semantics.rs#L949-L962

Furthermore, as we improve support for designators, for example including type checking, this refactoring will be even more important.

### PR DESCRIPTION
**Pull request by abhamra**
Fixes #170: minor changes because error handling for designators within this file wasn't standardized and should stay separated.

### CODE REVIEW

**Comment by jlapeyre** [comment]
This PR has a merge conflict. probably because main was updated. I think the updated main branch will fix the CI failure above.

**Comment by abhamra** [comment]
> This PR has a merge conflict. probably because main was updated. I think the updated main branch will fix the CI failure above.

Just rebased my fork, ideally should have fixed the issues.

**Comment by jlapeyre** [comment]
It's more convenient for the feature branch to have a name other than `main`. For example, I already have a local branch named `main`.

This PR should be rebased on the latest `main`, which includes #221

**Comment by abhamra** [comment]
@jlapeyre I see what you mean; I'm reasonably confident I have the changes from main, I think I will make a new PR with a new branch name that doesn't conflict, something like `from_designator_fix`. The code should be unchanged, just a new PR without the conflict.

**Comment by jlapeyre** [comment]
Obsolete. Replaced by #224

**Pull request closed without merging**
