### PR TITLE
Define U gate before parsing

### PR DESCRIPTION
**Pull request by jlapeyre**
This adds a bogus gate definition for U, which is required to be built in. This appears as the first statement in the ASG.

This is perhaps not the best way to handle the built in gate. But it doesn't touch much code. It can be changed to something better without too much trouble.

### CODE REVIEW

**Comment by jlapeyre** [comment]
Since `U` is required by the language spec, I am thinking it may be better to treat this specially rather than always sticking it in the ASG.

This would require an explicit check in a gate call. Also an explicit check every time a symbol is bound (If I recall correctly you are not allowed to shadow `U`).

**Comment by jakelishman** [comment]
> If I recall correctly you are not allowed to shadow `U`

I think the scoping rules are no different from any other global-scope identifier (if I remember right), in that you can shadow it with a variable in an inner scope, but not in the global scope.  But equally, if it's easier to treat it as reserved for the time being, I don't think that's an onerous request for people.

**Comment by jlapeyre** [comment]
My mention of shadowing is a bit of a red herring. In fact, we can treat U as reserved (with special handling for checking semantics of calls); and at the same time allow it to be shadowed where the spec allows.

**Comment by jlapeyre** [comment]
* Closing this in favor of #68

#68 is cleaner, smaller, and more efficient.

**Pull request closed without merging**
